trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'my-simple-image'

stages:
  - stage: Build
    jobs:
      - job: DockerBuild
        steps:
          - task: Checkout@1

          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              command: 'build'
              repository: '$(imageName)'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
